name: 'Trdl publish'
description: 'Publish releases defined in the project repository configuration (configuration file trdl_channels.yaml in the trdl branch by default)'
inputs:
  vault-addr:
    description: 'Address of the vault server running one or more vault-plugin-secrets-trdl instances'
    required: true
  project-name:
    description: 'Project name, which is vault-plugin-secrets-trdl mount point instance'
    required: true
  vault-auth-method:
    description: 'Select auth method to perform login into vault to get client token. Supported methods: approle'
  vault-role-id:
    description: 'Role ID for an approle auth method'
  vault-secret-id:
    description: 'Secret ID for an approle auth method'
  vault-token:
    description: 'Specify client token to perform vault requests'

runs:
  using: 'node12'
  main: '../dist/actions/publish/index.js'
