name: "Trdl releaser"
description: "Release project git tag using trdl build server"
inputs:
  vault-addr:
    description: "Address of the vault server running one or more vault-plugin-secrets-trdl instances"
    required: true
  project-name:
    description: "Project name, which is vault-plugin-secrets-trdl mount point instance"
    required: true
  git-tag:
    description: "Git tag of the application repository which will be used to build a release"
    required: true
  vault-auth-method:
    description: "Select auth method to perform login into vault to get client token. Supported methods: approle"
  vault-role-id:
    description: "Role ID for an approle auth method"
  vault-secret-id:
    description: "Secret ID for an approle auth method"
  vault-token:
    description: "Specify client token to perform vault requests"
  retry:
    description: |
      A flag that determines whether retries should be enabled in case of failure. 
      If set to `true`, the system will retry failed operations with an increasing backoff delay until either the operation succeeds or the maximum delay (`maxDelay`) is reached.
      If set to `false`, no retries will occur, and the task will immediately fail upon encountering an error.
    required: false
    default: "true"
  maxDelay:
    description: |
      The maximum delay time in seconds to be used for retries (backoff). 
      If the `retry` flag is set to `true`, this parameter defines the maximum amount of time
      the task will wait between each retry in case of failure.
      If the `retry` flag is set to `false`, backoff will not be applied.
      default: 6 hours (equals to github job timeout)
    required: false
    default: "21600"

runs:
  using: "node12"
  main: "../dist/actions/release/index.js"
